name: Barbara Bellissimo
favicon: null
layout_spectrum: 0.24791
typography_spectrum: 0.17903104587458074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffb800'
    - '#ff0074'
    - '#ff4e9b'
    - '#64613d'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.3634748167824
  rhythmicContrast: 0.25
purpose: []
